//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alibi
    {
        public int Alibi_id { get; set; }
        public string Text { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Complaint_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Сomplaint Сomplaint { get; set; }
    }
}
