//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сomplaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сomplaint()
        {
            this.Alibi = new HashSet<Alibi>();
        }
    
        public int Compaint_id { get; set; }
        public string Text { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Criminal_id { get; set; }
        public Nullable<int> Status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alibi> Alibi { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
